version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mm2d3d-api
    container_name: mm2d3d-api
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - mm2d3d

networks:
  mm2d3d:
    driver: bridge
